
# This is a basic workflow to help you get started with Actions

name: Pages deploy

# Controls when the action will run.
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Build
        run: |
          npm install
          npm run build
      - name: upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./dist/
          destination: ${{ secrets.GCP_BUCKET_NAME }}
          credentials: ${{ secrets.GCP_SA_KEY }}
